#!/bin/bash

set -e

BUILDDIR=/dev/shm
GRMLVER=0.17.4

sudo apt update
sudo apt install -y zsh

cd $BUILDDIR
wget https://deb.grml.org/pool/main/g/grml-etc-core/grml-etc-core_$GRMLVER.tar.gz
tar -xf grml-etc-core_$GRMLVER.tar.gz
cd grml-etc-core-$GRMLVER

sudo install -Dm644 etc/skel/.zshrc /etc/skel/.zshrc
sudo install -Dm644 etc/zsh/keephack /etc/zsh/keephack
sudo install -Dm644 etc/zsh/zshrc /etc/zsh/zshrc

cd $BUILDDIR
git clone https://github.com/zsh-users/zsh-autosuggestions.git 
cd zsh-autosuggestions
git checkout ae315ded4dba10685dbbafbfa2ff3c1aefeb490d
sudo install -Dm644 zsh-autosuggestions{,.plugin}.zsh -t /usr/share/zsh/plugins/zsh-autosuggestions/

cd $BUILDDIR
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
cd zsh-syntax-highlighting
git checkout 415e762ab21da7e0ebfe6dab09b8cc62df99bfcc
make
sudo make PREFIX="/usr" SHARE_DIR="/usr/share/zsh/plugins/zsh-syntax-highlighting" install

echo 'source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' | sudo tee -a /root/.zshrc
echo 'source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' | sudo tee -a /root/.zshrc
echo 'source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' | tee -a /home/kzl/.zshrc
echo 'source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' | tee -a /home/kzl/.zshrc

# environment variables
cat > ~/.zshenv << EOF 
typeset -U PATH path
path=("$HOME/.local/bin" "\$path[@]")
export PATH
EOF
