#!/bin/bash
#
# lfs-chroot.sh
#

set -e
set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

### libraries
. "$SCRIPT_DIR"/../lib/log.sh
. "$SCRIPT_DIR"/../lib/utils.sh
. "$SCRIPT_DIR"/../lib/chroot.sh

### checks
check_root

### constants & variables
rootfs_dir="$1"
shift

if [[ ! -d "$rootfs_dir" ]]; then
    error "Root filesystem directory '$rootfs_dir' does not exist." 1
fi

trap chroot_teardown EXIT SIGINT SIGTERM SIGKILL
chroot_setup "$rootfs_dir"
chroot_run "$rootfs_dir" "$@"
trap - EXIT SIGINT SIGTERM SIGKILL
chroot_teardown

### error codes
# 1: must be run as root
