#!/usr/bin/bash
#
# build.sh
#

set -e
# set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$0"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
BASH_LIB_DIR=${BASH_LIB_DIR:-"/home/kzl/LFS/bash/lib"}

################################################################################

### libraries
. "$BASH_LIB_DIR"/log.sh
. "$BASH_LIB_DIR"/pacman.sh
. "$SCRIPT_DIR"/lib/pkglists.sh

### constants & variables
VERSION="1.0"

LOG_DIR="$HOME"/makepkg/log

single_package=""
repo=""
declare -i stage
declare -i updatepkg=1
declare -i updated_only=0
declare -i install=0
declare -i no_clean=0
declare -i no_check=0

### functions
prepare() {
    info "Removing pacman cache and database..."
    sudo pacman -Scc --noconfirm || :
    info "Done"

    if [[ ! -e "$repo_path" ]]; then
        info "Creating empty repo \"$repo\" on \"$repo_path\"..."
        updaterepo -r "$repo"
        info "Done"
    fi

    info "Synchronizing package databases..."
    sudo pacman -Syy --noconfirm
    info "Done"

    mkdir -p -- "$LOG_DIR"
}

build() {
    local _pkgname="$1"
    local _pkgbase=$(get_pkgbase "$_pkgname")
    local _log
    local -i _updated=0
    local _cleanbuild='-C'
    local _clean='--clean'
    local _no_check='--nocheck'

    if [[ -n "$stage" ]]; then
        _log="$LOG_DIR/stage$stage.$_pkgbase.log"
    else
        _log="$LOG_DIR/$_pkgbase.log"
    fi

    if [[ -f "$_log" ]]; then
        mv "$_log" "${_log/.log/.old.log}"
    fi

    cd "$LFS_PACMAN_ROOT_DIR/pkgbuilds/$repo/$_pkgbase"

    if [[ -f "install-dependencies.sh" ]]; then
        info "Installing dependencies..."
        ./install-dependencies.sh >> "$_log" 2>&1
        info "Done"
    fi

    # update pkgbuild
    if (( $updatepkg > 0 )); then
        info "Updating PKGBUILD..."
        updatepkg --syncdeps >> "$_log" 2>&1 || _updated=$?
        _cleanbuild='-e'

        if (( $_updated == 255 )); then
            warn "  Current version is newer"
        elif (( $_updated == 0 )); then
            info "  No update for PKGBUILD"
        elif (( $_updated == 1 )); then
            info "  Package \"$_pkgbase\" is updated to new version"
        elif (( $_updated == 2 )); then
            error "  PKGBUILD does not exist" 5
        elif (( $_updated == 3 )); then
            warn "  PKGUPDATE does not exist"
            _cleanbuild='-C'
        elif (( $_updated >= 4 )); then
            error "  Cannot update the PKGBUILD (error code: $_updated)" 5
        else
            error "  Unknown \`updatepkg\` result" 5
        fi

        if (( $updated_only > 0 )) && (( $_updated == 0 || $_updated == 255 )); then
            # Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)
            info "Skip"
            return
        fi
        if (( $_updated == 0 )); then
            updatepkg -I >> "$_log" 2>&1
        fi
        info "Done"
    fi

    info "Building package..."
    if (( $no_check == 0 )); then
        _no_check=''
    fi
    if (( $no_clean > 0 )); then
        _clean=''
    fi

    makepkg -s -r "$_cleanbuild" -f "$_clean" "$_no_check" --noconfirm --log >> "$_log" 2>&1
    info "Done"

    info "Getting package configuration log..."
        sed -n '/^  -> Configuring...$/,/^  -> Compiling...$/{/^  -> Configuring...$/b;/^  -> Compiling...$/b;p}' "$_log" > config.txt
        if [[ ! -s "config.txt" ]]; then
            rm config.txt
        fi
    info "Done"

    info "Updating repo..."
    updaterepo -r "$repo" >> "$_log" 2>&1
    sudo pacman -Sy >> "$_log" 2>&1
    info "Done"

    if (( $install > 0 )); then
        info "Installing package..."
        local -a _pkgnames=($(get_pkgnames "$_pkgname"))
        # sudo pacman -Sddy --noconfirm --overwrite "*" "${_pkgnames[@]}" --config $pacman_conf >> "$_log" 2>&1
        sudo pacman -S --noconfirm ${_pkgnames[@]} >> "$_log" 2>&1
        echo "Package Contents:" >> "$_log" 2>&1
        pacman -Ql "${_pkgnames[@]}" >> "$_log" 2>&1
        info "Done"
    fi
}

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -V | --version
Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME -r <repo> -s <stage> | -p <pkgname> [ -n | -u ] [ --no-clean ] [ --no-check ]

    -V, --version               display version information and exit
    -h, --help                  display this help message and exit
    -r, --repo                  target repository (kzl, ubuntu, ...)
    -s, --stage                 target stage (0, 1(default), 2, 3; some repo are not using this)
    -p, --package               build single package
    -i, --install               install the package after building
    -n, --no-updatepkg          do not update the PKGBUILD before building
    -u, --updated-only          build the package only if the PKGBUILD is updated
    --no-clean                  skip cleaning up work files after build
    --no-check                  do not run the check() function in the PKGBUILD

EOF
}

################################################################################

while (( $# > 0 )); do
    case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    -r|--repo)
        shift
        repo="$1"
        ;;
    -s|--stage)
        shift
        stage="$1"
        ;;
    -p|--package)
        shift
        single_package="$1"
        ;;
    -i|--install)
        install=1
        ;;
    -n|--no-updatepkg)
        updatepkg=0
        ;;
    -u|--build-only-updated)
        updated_only=1
        ;;
    --no-clean)
        no_clean=1
        ;;
    --no-check)
        no_check=1
        ;;
    *)
        usage
        error "Unknown option: \"$1\"" 255
        ;;
    esac
    shift
done

case "$repo" in
    kzl)
        ;;
    ubuntu)
        ;;
    *)
        error "Unknown repo name \"$repo\"" 3
        ;;
esac

if (( $updatepkg == 0 )) && (( $updated_only == 1 )); then
    error "Cannot use --updated-only together with --no-updatepkg" 6
fi

if [[ -n "$single_package" ]]; then
    if [[ -n "$stage" ]]; then
        error "Cannot use -s | --stage together with -p | --package" 2
    fi
else
    stage=${stage:-1}
    case "$repo" in
        kzl)
            case "$stage" in
                0)
                    # updaterepo --clear -r "$repo"
                    pkgs=("${kzl_stage0_pkgs[@]}")
                    ;;
                1)
                    pkgs=("${kzl_stage1_pkgs[@]}")
                    ;;
                2)
                    pkgs=("${kzl_stage2_pkgs[@]}")
                    ;;
                3)
                    pkgs=("${kzl_stage3_pkgs[@]}")
                    ;;
                *)
                    error "Unknown stage \"$stage\"" 4
                    ;;
            esac
            ;;
        ubuntu)
            case "$stage" in
                1)
                    pkgs=("${ubuntu_stage1_pkgs[@]}")
                    ;;
                2)
                    pkgs=("${ubuntu_stage2_pkgs[@]}")
                    ;;
                *)
                    error "Unknown stage \"$stage\"" 4
                    ;;
            esac
            ;;
        *)
            error "Unknown repo name \"$repo\"" 3
            ;;
    esac
fi

repo_path="/home/.repository/$repo/$repo.db.tar.zst"

################################################################################

prologue

prepare
if [[ -n "$single_package" ]]; then
    # Build a single package
    log_magenta "Building $single_package ($(date +%H:%M:%S))..."
    __pkg_start_time__=$(date +%s)
    build "$single_package"
    __pkg_end_time__=$(date +%s)
    __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
    log_cyan "Finished $single_package: $(date -d "@$__pkg_total_time__" +%H:%M:%S) ($(date +%H:%M:%S))"
else
    log_blue "Building stage $stage ($(date +%H:%M:%S))..."
    for p in ${pkgs[@]}; do
        log_magenta "Building $p ($(date +%H:%M:%S))..."
        __pkg_start_time__=$(date +%s)
        build "$p"
        __pkg_end_time__=$(date +%s)
        __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
        log_cyan "Finished $p: $(date -d "@$__pkg_total_time__" +%H:%M:%S) ($(date +%H:%M:%S))"
    done
fi

epilogue

### error codes
# 2: cannot use -s | --stage together with -p | --package
# 3: unknown repo name
# 4: unknown stage
# 5: cannot update the PKGBUILD
# 6: cannot use --updated-only together with --no-updatepkg
# 255: unknown option
