#!/usr/bin/bash
#
# build.sh
#
# TODO: build only updated pkgs

script_name="$(basename "${0}")"
stage=1
build_dir=/tmp
repo=kzl
log_dir=$build_dir
repo_dir=/home/.repository/$repo

# preparation
kzl_stage0_pkgs=(
)

# toolchain
kzl_stage1_pkgs=(
)

# base
kzl_stage2_pkgs=(
    ### base
    ## filesystem
    iana-etc tzdata # filesystem
)

kzl_stage3_pkgs=(
)

# functions

# Show an INFO message
# $1: message string
info() {
    local _msg="$1"
    printf '[%s] INFO: %s\n' "$script_name" "$_msg"
}

# Show a WARNING message
# $1: message string
warning() {
    local _msg="$1"
    printf '[%s] WARNING: %s\n' "$script_name" "$_msg" >&2
}

# Show an ERROR message then exit with status
# $1: message string
# $2: exit code number (with 0 does not exit)
error() {
    local _msg="$1"
    local _error="$2"
    printf '[%s] ERROR: %s\n' "$script_name" "$_msg" >&2
    if (( _error > 0 )); then
        exit "$_error"
    fi
}

prepare() {
    info "Removing pacman cache and database..."
    (yes yes || :) | sudo pacman -Scc > /dev/null 2>&1

    if [ ! -f /home/.repository/$repo/$repo.db ]; then
        info "Creating empty repo \"$repo\"..."
        update-repo -t $repo > /dev/null 2>&1
    fi
    info "Synchronizing package databases..."
    (yes yes || :) | sudo pacman -Syy > /dev/null 2>&1
}

get_pkgbase() {
    local _pkgbase
    case $1 in
        device-mapper)
            _pkgbase=lvm2
            ;;
        *)
            _pkgbase=$1
            ;;
    esac
    echo "$_pkgbase"
}

build() {
    local _pkgbase
    local _pkgname
    local _updated
    local _log

    _pkgname=$1
    _pkgbase=$(get_pkgbase $_pkgname)
    _log="$log_dir"/$_pkgbase.stage$stage.log

    cd $ROOTDIR/pkgbuilds/$repo/$_pkgbase

    # update pkgbuild
    info "Updating PKGBUILD..."
    updatepkg >> $_log 2>&1

    # remove existing log
    if [ -f $_log ]; then
        rm $_log
    fi

    info "Building package..."
    makepkg -scCf --noconfirm --nocheck >> $_log 2>&1

    info "Updating repo..."
    update-repo -t $repo >> $_log 2>&1

    info "Installing package..."
    # (yes yes || :) | sudo pacman -Sddy --overwrite "*" $_pkgname --config ${pacman_conf}
    (yes yes || :) | sudo pacman -Sddy --overwrite "*" $_pkgname >> $_log 2>&1
}

usage() {
    local _usage="
build (kzl-linux)

build will build packages from scratch.

Usage: lfs-build [options]

    -h, --help      display this help message and exit
    -r, --repo      target repository (kzl, testing, ...)
    -s, --stage     stage (0, 1(default), 2, 3)
    -v, --version   display version information and exit
"
    echo "$_usage"
}

################################################################

set -e
set -o pipefail
set -u
# set -x

umask 0022

while [ $# -gt 0 ]; do
    case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    -r|--repo)
        shift
        repo="$1"
        ;;
    -s|--stage)
        shift
        stage="$1"
        ;;
    *)
        usage
        echo "Unknown option: \"$1\""
        exit 1
        ;;
    esac
    shift
done

case $repo in
    kzl)
        case $stage in
        0)
            update-repo --clear -t $repo
            pkgs=${kzl_stage0_pkgs[@]}
            ;;
        1)
            pkgs=${kzl_stage1_pkgs[@]}
            ;;
        2)
            echo -e "\033[1;33mBuilding stage 2\033[0m"
            pkgs=${kzl_stage2_pkgs[@]}
            ;;
        3)
            pkgs=${kzl_stage3_pkgs[@]}
            ;;
        *)
            printf "Unknown stage \"$stage\""
            exit 1
            ;;
        esac
        ;;
    *)
        echo "Unknown repo name \"$repo\""
        exit 2
        ;;
esac

start_time=$(date +%s)

prepare

for p in ${pkgs[@]}; do
    pkg_start_time=$(date +%s)
    echo -e "\e[1;31mBuilding $p ...\e[0m"
    build $p
    pkg_end_time=$(date +%s)
    pkg_total_time=$((pkg_end_time-pkg_start_time))
    echo -e "\e[1;32m$p: $(date -d@$pkg_total_time -u +%H:%M:%S)\e[0m"
done

end_time=$(date +%s)
total_time=$((end_time-start_time))

echo -e "\e[1;30m"
echo -e "****************************************************************"
echo -e "                Execution time Information                "
echo -e "****************************************************************"
echo -e "[$script_name]: End time - $(date)"
echo -e "[$script_name]: Total time - $(date -d@$total_time -u +%H:%M:%S)"
echo -e "\e[0m"
