#!/usr/bin/bash

script_name="$(basename "${0}")"

set -e -o pipefail -u

eval $(grep SRCDEST /etc/makepkg.conf)

have_function() {
	declare -f "$1" >/dev/null
}

unset new_version old_version remove_old_sources
source PKGUPDATE

result=$(vercmp $new_version $old_version)

if [ $result -gt 0 ]; then
    printf '[%s] PKGBUILD updated: %s => %s\n' "$script_name" "$old_version" "$new_version"
    sed -i "/^pkgver=/s/$old_version/$new_version/" PKGBUILD
    if have_function 'remove_old_sources'; then
        remove_old_sources
    fi
fi

updpkgsums
