#!/usr/bin/bash
#
# updaterepo.sh
#

set -e
set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
BASH_LIB_DIR=${BASH_LIB_DIR:-"/home/kzl/LFS/bash/lib"}

################################################################################

### libraries
source "$BASH_LIB_DIR"/log.sh
source "$BASH_LIB_DIR"/pacman.sh

### constants & variables
REPO_ROOT="/home/.repository"
PACKAGE_DIR="$HOME/makepkg/packages"
ARCHIVE_DIR="$HOME/makepkg/archive"

declare -i replace=0
declare -i clear=0
repo=""

### functions
update() {
    local _pkg="$1"
    local _pkg_file="$(get_pkg_file "$_pkg" "$PACKAGE_DIR")"

    mkdir -p -- "$ARCHIVE_DIR"

    if [[ -f "$PACKAGE_DIR/$_pkg_file" ]]; then
        sudo cp -f -- "$PACKAGE_DIR/$_pkg_file" "$repo_dir"
        mv -- "$PACKAGE_DIR/$_pkg_file" "$ARCHIVE_DIR"
        sudo repo-add -R "$repo_path" "$repo_dir/$_pkg_file"
    fi
}

usage() {
    cat <<EOF

updaterepo

Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME -R | --replace -r | --repo <core|extra|ubuntu>
Usage: $SCRIPT_NAME -c | --clear -r | --repo <core|extra|ubuntu>

    -h, --help      display this help message and exit
    -r, --repo      build repo (core, extra, ubuntu)
    -R, --replace   replace the existing repository file with an empty one
    -c, --clear     remove the repository

EOF
}

################################################################################

while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -r|--repo)
            shift
            repo="$1"
            ;;
        -R|--replace)
            replace=1
            ;;
        -c|--clear)
            clear=1
            ;;
        *)
            error "Unknown option \"$1\"" 127
            ;;
    esac
    shift
done

case "$repo" in
    kzl|ubuntu)
        readarray -t pkgs < <(find "$LFS_PACMAN_ROOT_DIR/pkgbuilds/$repo/" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | LC_ALL=C sort -n)
        ;;
    # unknown repo
    *)
        error "Unknown repo \"$repo\"." 127
        ;;
esac
repo_dir="$REPO_ROOT/$repo"
repo_path="$repo_dir/$repo.db.$EXTENSION"

### clear
if (( $clear > 0 )); then
    while true; do
        read -p "Do you want to clear the repository \"$repo\"? " yn
        case "$yn" in
            [Yy]*)
                sudo rm -vrf -- "$repo_dir"
                # sudo find "$repo_dir" -type f -delete
                info "Repository \"$repo\" has been removed"
                exit 0
                ;;
            [Nn]*)
                exit 0
                ;;
            *)
                echo "Please answer yes(y) or no(n)."
                ;;
        esac
    done
fi

if [[ ! -d "$repo_dir" ]]; then
    sudo mkdir -p -- "$repo_dir"
fi

if (( $replace > 0 )); then
    sudo find "$repo_dir" -name "*.pkg.$EXTENSION" -exec mv -v -t "$PACKAGE_DIR" -- {} +
    sudo chown -R -- "$(stat -c '%U:%G' "$PACKAGE_DIR")" "$PACKAGE_DIR"
    sudo find "$repo_dir" -mindepth 1 -delete
fi

if [[ ! -f "$repo_path" ]]; then
    info "Creating empty repo: $repo.db.$EXTENSION..."
    sudo repo-add "$repo_path"
    info "Done"
fi

################################################################################

for pkgbase in "${pkgs[@]}"; do
    info "Updating $pkgbase..."
    update "$pkgbase"
    case "$pkgbase" in
        zlib)
            update minizip
            ;;
        audit)
            update python-audit
            ;;
        lvm2)
            update device-mapper
            ;;
        linux)
            update linux-headers
            ;;
        lapack)
            update blas
            update cblas
            update lapacke
            ;;
    esac
done

if [[ -z $(find "$PACKAGE_DIR" -empty) ]]; then
   warn "$PACKAGE_DIR is not empty, please check"
fi

### error codes
# 2: Unknown repo
# 3: Multiple packages with the same name are found
# 127: Unknown option
