#!/bin/bash


# Prevent p11-kit from reading user configuration files.
export P11_KIT_NO_USER_CONFIG=1

DEST=/etc/ca-certificates/extracted


/usr/bin/trust extract --filter=certificates --format=openssl-bundle --overwrite --comment "$DEST"/ca-bundle.trust.crt

/usr/bin/trust extract --filter=ca-anchors --format=pem-bundle --overwrite --comment --purpose=server-auth "$DEST"/tls-ca-bundle.pem

/usr/bin/trust extract --filter=ca-anchors --format=pem-directory-hash --overwrite --purpose=server-auth --comment "$DEST"/pem-directory-hash

for certs in "$DEST"/pem-directory-hash/*; do
  ln -srf -t /etc/ssl/certs "$certs"
done

# Compatibility link for legacy bundle (Debian)
ln -srf "$DEST"/tls-ca-bundle.pem /etc/ssl/certs/ca-certificates.crt

# Find and remove all broken symlinks
find -L /etc/ssl/certs -maxdepth 1 -type l -delete
