#!/bin/bash
#
# template.sh
#

set -e
set -o pipefail
set -u
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(realpath "$0")"
# SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

# unset __DEBUG__
# __DEBUG__=1

### general libraries
. "$SCRIPT_DIR"/lib/log.sh
. "$SCRIPT_DIR"/lib/utils.sh
# . "$SCRIPT_DIR"/lib/loop.sh
# . "$SCRIPT_DIR"/lib/chroot.sh

### checks
# if [[ $EUID -ne 0 ]]; then
#     error "This script must be run as root" 255
# fi
check_root

### constants & variables
declare -r VERSION="1.0"

variable="value"

### options and arguments
declare -i opt_verbose=0
arg_input=""

### domain specific libraries
# . "$SCRIPT_DIR"/lib/mkiso.sh

### functions
example_function() {
    info "example_function"

    sleep 1

    echo "$arg_input"
}

clean() {
    info "clean"

    trap - EXIT SIGINT SIGTERM SIGKILL
}
trap clean EXIT SIGINT SIGTERM SIGKILL
# trap "trap - SIGTERM && kill -- -$$" EXIT SIGINT SIGTERM SIGKILL

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -V | --version
Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME [-v | --verbose ] -i | --input <arg>

    -V, --version                   print the script version number and exit
    -h, --help                      print this help message and exit
    -i, --input <arg>               argument
    -v, --verbose                   verbose

EOF
}

################################################################################

# while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
#     case "$1" in
#     -V | --version )
#         echo "$version"
#         exit
#         ;;
#     -h | --help)
#         usage
#         ;;
#     -i | --input)
#         shift
#         if [[ -z "$1" || "$1" =~ ^- ]]; then
#             error "Missing value for input"
#         fi
#         arg_input="$1"
#         ;;
#     -v | --verbose)
#         shift; opt_verbose=1
#         ;;
#     *)
#         usage
#         error "Unknown option: $1"
#         ;;
#     esac
#     shift
# done
# if [[ "$1" == '--' ]]; then shift; fi

while (( $# > 0 )); do
    case "$1" in
    -V | --version)
        echo "$VERSION"
        exit
        ;;
    -h | --help)
        usage
        ;;
    -i | --input)
        shift
        arg_input="$1"
        ;;
    -v | --verbose)
        shift
        opt_verbose=1
        ;;
    *)
        usage
        error "Unknown option: $1" 128
        ;;
    esac
    shift
done

################################################################################

prologue

example_function
clean

epilogue

### error codes
# 1: general error
# 2-126: specific error codes
# 127: command not found
# 128: unknown option or invalid argument
# 255: must be run as root
