#!/usr/bin/bash
#
# kzl-chroot.sh
#

set -e
set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
BASH_LIB_DIR=${BASH_LIB_DIR:-"/home/kzl/LFS/bash/lib"}

################################################################################

### libraries
source "$BASH_LIB_DIR"/log.sh
source "$BASH_LIB_DIR"/chroot.sh

### constants & variables
rootfs_dir="$1"
shift

trap chroot_teardown EXIT SIGINT SIGTERM SIGKILL
chroot_setup "$rootfs_dir"
SHELL=/bin/bash LC_ALL=C PATH="$CHROOT_PATH" unshare --fork --pid chroot "$rootfs_dir" "$@"
chroot_teardown
