#!/bin/bash

set -e
set -o pipefail
set -u
# set -x

cp /etc/ssh/sshd_config rootfs/etc/ssh/
sed -e '/^#PermitRootLogin/c\PermitRootLogin yes' \
    -e '/^#PermitEmptyPasswords/c\PermitEmptyPasswords yes' \
    -i rootfs/etc/ssh/sshd_config

# grml-zsh-config
wget -O rootfs/root/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

mkdir -p rootfs/root/.zsh

sudo rm -rf rootfs/root/.zsh/zsh-syntax-highlighting
git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git rootfs/root/.zsh/zsh-syntax-highlighting
rm -rf rootfs/root/.zsh/zsh-syntax-highlighting/{.git,.github,docs,images,tests,.editorconfig,.gitattributes,.gitignore,*.md,Makefile}
find rootfs/root/.zsh/zsh-syntax-highlighting -name '*.md' -delete
find rootfs/root/.zsh/zsh-syntax-highlighting -name 'test-data' -exec rm -rf {} +

sudo rm -rf rootfs/root/.zsh/zsh-autosuggestions
git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git rootfs/root/.zsh/zsh-autosuggestions
rm -rf rootfs/root/.zsh/zsh-autosuggestions/{.circleci,.git,.github,spec,.editorconfig,.rspec,.rubocop.yml,.ruby-version,DESCRIPTION,Dockerfile,Gemfile*,install_test_zsh.sh,LICENSE,URL,VERSION,ZSH_VERSIONS,*.md,Makefile}

echo 'source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' >> rootfs/root/.zshrc
echo 'source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh' >> rootfs/root/.zshrc
