#!/usr/bin/bash
#
# update-rootfs.sh
#

set -e
set -o pipefail
set -u
# set -x

################################################################################

cp /etc/ssh/sshd_config rootfs/etc/ssh/
sed -e '/^#PermitRootLogin/c\PermitRootLogin yes' \
    -e '/^#PermitEmptyPasswords/c\PermitEmptyPasswords yes' \
    -i rootfs/etc/ssh/sshd_config

# grml-zsh-config
rm -rf rootfs/root/.zsh
mkdir -p rootfs/root/.zsh
wget -O rootfs/root/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

rm -rf rootfs/root/zsh-syntax-highlighting
git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git rootfs/root/zsh-syntax-highlighting
pushd rootfs/root/zsh-syntax-highlighting
make
make PREFIX="../.zsh/" SHARE_DIR="../.zsh/" DOC_DIR="../.zsh/doc" install
popd
rm -rf rootfs/root/zsh-syntax-highlighting


rm -rf rootfs/root/zsh-autosuggestions
git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git rootfs/root/zsh-autosuggestions
pushd rootfs/root/zsh-autosuggestions
make
install -Dm644 zsh-autosuggestions{,.plugin}.zsh -t ../.zsh/
popd
rm -rf rootfs/root/zsh-autosuggestions

rm -rf rootfs/root/.zsh/doc

echo 'source ~/.zsh/zsh-syntax-highlighting.zsh' >>rootfs/root/.zshrc
echo 'source ~/.zsh/zsh-autosuggestions.zsh' >>rootfs/root/.zshrc
