#!/bin/bash
#
# mkimg
#
# https://cdimage.ubuntu.com/releases/
#


set -e
set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

unset __DEBUG__
__DEBUG__=1

### general libraries
. "$SCRIPT_DIR"/lib/log.sh
. "$SCRIPT_DIR"/lib/utils.sh
. "$SCRIPT_DIR"/lib/chroot.sh
. "$SCRIPT_DIR"/lib/loop.sh
. "$SCRIPT_DIR"/lib/deb.sh

### checks
check_root

### constants and variables
declare -r TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

declare -r WORK_DIR="/tmp/raspi_$TIMESTAMP"
declare -r ROOTFS_DIR="$WORK_DIR/rootfs"
declare -r LOG_DIR="$WORK_DIR/log"

declare -r CONFIG_DIR="$SCRIPT_DIR/config"
declare -r PKGLIST_DIR="$SCRIPT_DIR/pkglist"

declare -r IMG_FILE="$WORK_DIR/raspi.img"
declare -r RASPBERRYPI_GPG_KEY="$WORK_DIR/raspberrypi.gpg.key"

common_deb_pkgs=(
    ### general
    sudo
    file
    build-essential
    ### disk
    parted
    ### network
    iw wpasupplicant
    rfkill
    ### kernel
    # initramfs-tools
)
debian_deb_pkgs=(
    systemd-resolved
    systemd-timesyncd
    bluez
    ### firmware
    firmware-brcm80211
    firmware-realtek
    bluez-firmware
    ### raspi
    raspberrypi-archive-keyring
    raspberrypi-sys-mods
    raspberrypi-net-mods
    raspi-config
    raspi-firmware
    raspi-gpio
    raspi-utils
    rpi-eeprom
    # rpicam-apps-lite
)
ubuntu_deb_pkgs=(
    linux-firmware-raspi2
    ubuntu-raspi-settings
)

loop_device=""
deb_pkgs=()

img_file=""

### options and arguments
arg_rootfs_tarball=""
arg_chroot_image=""
arg_chroot_command=()

### functions
cleanup() {
    set +e

    if [[ -d "$WORK_DIR" ]]; then
        log_magenta "Cleaning up..."
        chroot_teardown
        loop_teardown "$loop_device"

        local _answer
        read -t 10 -p "Do you want to remove the working directory $WORK_DIR? (y/N) " _answer
        if [[ "$_answer" == "Y" || "$_answer" == "y" ]]; then
            log_magenta "Removing working directory: $WORK_DIR"
            rmdir -v -- "$ROOTFS_DIR" && rm -rf --one-file-system -- "$WORK_DIR" >&2
            log_magenta "Done (Removed working directory)"
        fi
        log_magenta "Done (Cleaned up)"
    fi

    trap - EXIT SIGINT SIGTERM SIGKILL
}
trap cleanup EXIT SIGINT SIGTERM SIGKILL

make_work_dirs() {
    info "Making working directory: $WORK_DIR"
    if [[ -d "$WORK_DIR" ]]; then
        error "Working directory $WORK_DIR already exists" 1
    fi
    mkdir -vp -- "$WORK_DIR"
    mkdir -vp -- "$ROOTFS_DIR"
    mkdir -vp -- "$LOG_DIR"
    if [[ ! -d "$PKGLIST_DIR" ]]; then
        mkdir -vp -- "$PKGLIST_DIR"
        chown ${SUDO_UID:-0}:${SUDO_GID:-0} -- "$PKGLIST_DIR"
    fi
    info "Done (Made root filesystem directory)"
}

make_img_file() {
    info "Making image..."

    if [[ -f "$IMG_FILE" ]]; then
        rm -vf "$IMG_FILE"
    fi

    fallocate -l 1536MiB "$IMG_FILE"

    parted -s "$IMG_FILE" \
        mktable msdos \
        unit s \
        mkpart primary fat32 1s 524287s \
        mkpart primary ext4 524288s 100% \
        print \
        > "$LOG_DIR/parted.log"
    info "Done (Made image file: $IMG_FILE)"
}

setup_loop() {
    local _img_file="$1"

    info "Setting up loop device for image: $_img_file"
    if [[ ! -f "$_img_file" && ! -b "$_img_file" ]]; then
        error "Image file does not exist: $_img_file" 2
    fi

    loop_device="$(loop_get_device)"
    if [[ -z "$loop_device" ]]; then
        error "No unused loop device found" 2
    fi
    loop_partitioned_setup "$loop_device" "$_img_file"
    info "Done (Setup loop device: $loop_device)"
}

format_img() {
    info "Formatting image..."
    if [[ -z "$loop_device" ]]; then
        error "Loop device is not set" 2
    fi
    mkfs.fat -F 32 -n "BOOT" "${loop_device}p1" > "$LOG_DIR/mkfs.fat.log"
    mkfs.ext4 -L "ROOT" "${loop_device}p2" > "$LOG_DIR/mkfs.ext4.log"
    info "Done (Formatted image)"
}

mount_img() {
    info "Mounting loop device..."
    mount "${loop_device}p2" "$ROOTFS_DIR"
    mkdir -vp -- "$ROOTFS_DIR"/boot/firmware
    mount "${loop_device}p1" "$ROOTFS_DIR"/boot/firmware
    info "Done (Mounted loop device)"
}

bootstrap_rootfs() {
    local _deb_pkgs_installed="$PKGLIST_DIR/${arg_suite}-rootfs-pkgs.txt"
    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkgs_installed"

    info "Extracting root filesystem..."
    tar -v \
        --zstd \
        --xattrs --acls \
        --numeric-owner \
        -xpf "$arg_rootfs_tarball" \
        -C "$ROOTFS_DIR" \
        > "$LOG_DIR/tar.log"
    info "Done (Extracted root filesystem)"

    if [[ "$distro" == "debian" ]]; then
        info "Setting up initial sources.list..."
        mkdir -p -- "$ROOTFS_DIR/etc/apt/sources.list.d"
        cat > "$ROOTFS_DIR/etc/apt/sources.list.d/raspi.sources" << EOF
Types: deb
URIs: https://archive.raspberrypi.com/debian/
Suites: $arg_suite
Components: main
Signed-By: /etc/apt/trusted.gpg.d/raspberrypi.gpg.key
#Signed-By: /etc/apt/trusted.gpg.d/raspberrypi-archive-stable.gpg
EOF
        # raspberrypi-archive-stable.gpg will be overwritten by deb package raspberrypi-archive-keyring
        wget -qO "$ROOTFS_DIR/etc/apt/trusted.gpg.d/raspberrypi.gpg.key" http://archive.raspberrypi.org/debian/raspberrypi.gpg.key
        info "Done (Set up initial sources.list)"
    fi

    info "Install deb packages..."
    deb_apt "$ROOTFS_DIR" deb_pkgs > "$LOG_DIR/apt.log"
    deb_get_installed_pkgs "$ROOTFS_DIR" > "$_deb_pkgs_installed"
    info "Done (Installed deb packages)"

    if [[ "$distro" == "debian" ]]; then
        info "Setting up sources.list..."
        rm -vf -- "$ROOTFS_DIR/etc/apt/trusted.gpg.d/raspberrypi.gpg.key"
        sed -i -e '/^Signed-By/d' -e '/^#Signed-By/s/^#//' "$ROOTFS_DIR/etc/apt/sources.list.d/raspi.sources"
        info "Done (Set up sources.list)"
    fi
}

configure_rootfs() {
    info "Downloading RPi firmware..."
    local _firmware_version=$(git ls-remote --tags https://github.com/raspberrypi/firmware.git | grep -oP '(?<=refs/tags/)1.\d{8}$' | sort -V | tail -n1)
    local _firmware_dir="$WORK_DIR/firmware-$_firmware_version"
    wget -qO "$WORK_DIR/firmware.tar.gz" https://github.com/raspberrypi/firmware/archive/refs/tags/$_firmware_version.tar.gz
    tar -xf "$WORK_DIR/firmware.tar.gz" -C "$WORK_DIR"
    info "Done (Downloaded RPi firmware: $_firmware_version)"

    info "Copying kernel images in raspberrypi/firmware to rootfs..."
    mv -- "$_firmware_dir"/boot/* "$ROOTFS_DIR/boot/firmware/"
    mv -- "$_firmware_dir"/modules "$ROOTFS_DIR/usr/lib/"
    local _kernel_version
    local _kv
    local _kernel_suffix
    local -a _kernel_version_suffix=()
    for _kernel_version in $(ls "$ROOTFS_DIR/usr/lib/modules"); do
        _kv=$(echo "$_kernel_version" | grep -oP '\d+\.\d+\.\d+\K.*' | sed 's/^-v//;s/\+//')
        case "$_kv" in
            8-16k)  _kernel_suffix="_2712" ;;
            *)      _kernel_suffix="$_kv" ;;
        esac
        cp -vdr -- "$ROOTFS_DIR/boot/firmware/kernel$_kernel_suffix.img" "$ROOTFS_DIR/boot/vmlinuz-$_kernel_version"
        _kernel_version_suffix+=("$_kernel_version:$_kernel_suffix")
    done
    info "Done (Copied kernel images)"

    info "Initializing rootfs..."
    chroot_setup "$ROOTFS_DIR"
    # chroot_run "$ROOTFS_DIR" update-initramfs -c -k all
    chroot_run "$ROOTFS_DIR" /bin/bash -e -u -o pipefail -s > "$LOG_DIR/initialize.log" << EOF
useradd -m -U -G adm,dialout,sudo,audio,video -s /bin/zsh kzl
echo "root:raspi" | chpasswd
echo "kzl:raspi" | chpasswd

systemctl disable wpa_supplicant.service
systemctl disable NetworkManager.service
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
systemctl enable wpa_supplicant@wlan0.service
systemctl enable ssh.service
EOF
    chroot_teardown
    rm -vf -- "$ROOTFS_DIR/initialize.sh"
    info "Done (Initialized rootfs)"

    # info "Copying initramfs..."
    # local _kvs
    # for _kvs in "${_kernel_version_suffix[@]}"; do
    #     _kernel_version=${_kvs%%:*}
    #     _kernel_suffix=${_kvs##*:}
    #     cp -dr "$ROOTFS_DIR/boot/initrd.img-$_kernel_version" "$ROOTFS_DIR/boot/firmware/initramfs$_kernel_suffix"
    # done
    # info "Done (Copied initramfs)"

    info "Copying miscellaneous config files..."
    # hostname
    echo "RPi" > "$ROOTFS_DIR/etc/hostname"
    # environment
    echo "PATH=\"/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/bin:/opt/sbin\"" > "$ROOTFS_DIR/etc/environment"
    cp -vf -- "$CONFIG_DIR/profile" "$ROOTFS_DIR/etc/profile"
    # passwd
    sed -i '/^root/s|/bin/bash|/bin/zsh|' "$ROOTFS_DIR"/etc/passwd
    # network
    cp -vf -- "$CONFIG_DIR/ethernet.network" "$ROOTFS_DIR/etc/systemd/network/ethernet.network"
    cp -vf -- "$CONFIG_DIR/wifi.network" "$ROOTFS_DIR/etc/systemd/network/wifi.network"
    cp -vf -- "$CONFIG_DIR/wpa_supplicant.conf" "$ROOTFS_DIR/etc/wpa_supplicant/wpa_supplicant.conf"
    ln -sf wpa_supplicant.conf "$ROOTFS_DIR/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
    # rfkill
    if [[ "$distro" == "debian" ]]; then
        sed -i 's/^options[[:space:]]\+rfkill[[:space:]]\+default_state=0$/options rfkill default_state=1/' \
            "$ROOTFS_DIR/etc/modprobe.d/rfkill_default.conf"
    fi
    # grml-zsh-config for root
    wget -O "$ROOTFS_DIR/root/.zshrc" https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc > "$LOG_DIR/grml-zsh-config.log" 2>&1
    echo '. /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' >> "$ROOTFS_DIR/root/.zshrc"
    echo '. /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh' >> "$ROOTFS_DIR/root/.zshrc"
    info "Done (Copied miscellaneous config files)"

    info "Cleaning up rootfs..."
    clean_rootfs "$ROOTFS_DIR" > "$LOG_DIR/clean_rootfs.log"
    info "Done (Cleaned up rootfs)"

    info "Copying boot configuration files..."
    # copy configuration files
    cp -vf -- "$CONFIG_DIR/config.txt" "$ROOTFS_DIR/boot/firmware/config.txt"
    # get PARTUUIDs of the partitions
    local _b_partuuid=$(findmnt -n -o PARTUUID --source "${loop_device}p1")
    local _r_partuuid=$(findmnt -n -o PARTUUID --source "${loop_device}p2")
    if [ -z "$_b_partuuid" ]; then
        error "Cannot find PARTUUID of BOOT partition!" 4
    fi
    info "BOOT PARTUUID: $_b_partuuid"
    if [ -z "$_r_partuuid" ]; then
        error "Cannot find PARTUUID of ROOT partition!" 4
    fi
    info "ROOT PARTUUID: $_r_partuuid"
    # set PARTUUIDs in fstab and cmdline.txt
    cat > "$ROOTFS_DIR/etc/fstab" << EOF
PARTUUID=$_r_partuuid       /                   ext4        defaults                0 1
PARTUUID=$_b_partuuid       /boot/firmware      vfat        defaults,noatime        0 2
#/swapfile                   none                swap        defaults                0 0
EOF
    cat > "$ROOTFS_DIR/boot/firmware/cmdline.txt" << EOF
console=serial0,115200 console=tty1 root=PARTUUID=$_r_partuuid rootfstype=ext4 fsck.repair=yes rootwait quiet init=/usr/lib/raspberrypi-sys-mods/firstboot
EOF
    if [[ "$distro" == "ubuntu" ]]; then
        sed -i -E 's| init=.*||' "$ROOTFS_DIR/boot/firmware/cmdline.txt"
    fi
    info "Done (Copied boot configuration files)"

    sync
}

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -V | --version
Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME -s | --suite <suite>  -r | --rootfs-tarball <tarball>
Usage: $SCRIPT_NAME -c | --chroot <image> [<command>]

    -h, --help                          print this help message and exit
    -s, --suite <suite>                 specify the image suite (bookworm, trixie, jammy)
    -r, --rootfs-tarball <tarball>      specify the root filesystem tarball to use
    -c, --chroot <image> [<command>]    chroot into the image file and run the command

EOF
}

################################################################################

while (( $# > 0 )); do
    case "$1" in
    -h | --help)
        usage
        exit 0
        ;;
    -s | --suite)
        shift
        arg_suite="$1"
        ;;
    -r | --rootfs-tarball)
        shift
        arg_rootfs_tarball="$1"
        ;;
    -c | --chroot)
        shift
        arg_chroot_image="$1"
        shift
        arg_chroot_command=("$@")
        break
        ;;
    *)
        usage
        error "Unknown option: $1" 128
        ;;
    esac
    shift
done

if [[ -z "$arg_chroot_image" ]]; then
    if [[ ! -f "$arg_rootfs_tarball" ]]; then
        error "Root filesystem tarball not found: $arg_rootfs_tarball" 1
    fi

    case "$arg_suite" in
        bookworm|trixie)
            distro="debian"
            deb_pkgs=("${common_deb_pkgs[@]}" "${debian_deb_pkgs[@]}")
            ;;
        jammy)
            distro="ubuntu"
            deb_pkgs=("${common_deb_pkgs[@]}" "${ubuntu_deb_pkgs[@]}")
            ;;
        *)
            usage
            error "Unsupported distribution \"$arg_suite\"." 2
            ;;
    esac

    img_file="raspi-$arg_suite-$TIMESTAMP.img"
fi


################################################################################

prologue

make_work_dirs

if [[ -n "$arg_chroot_image" ]]; then
    info "Chroot into image $arg_chroot_image, all previous arguments will be ignored"
    setup_loop "$arg_chroot_image"
    mount_img
    chroot_setup "$ROOTFS_DIR"
    chroot_run "$ROOTFS_DIR" "${arg_chroot_command[@]}"
    chroot_teardown
else
    make_img_file
    setup_loop "$IMG_FILE"
    format_img
    mount_img
    bootstrap_rootfs
    configure_rootfs
    mv -v -- "$IMG_FILE" "$SCRIPT_DIR/$img_file"
    log_cyan "Successfully made Raspberry Pi image: $img_file"
    chown ${SUDO_UID:-0}:${SUDO_GID:-0} -- "$SCRIPT_DIR/$img_file"
fi

cleanup

epilogue

### error code
# 1: general error
# 2: loop device
# 3: chroot environment
# 4: partition
# 128: Unknown option
# 255: Failed to remove work directories
