#!/bin/bash
#
# mkrootfs
#

set -e
set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$0"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

unset __DEBUG__
__DEBUG__=1

### libraries
. "$SCRIPT_DIR"/lib/log.sh
. "$SCRIPT_DIR"/lib/utils.sh
. "$SCRIPT_DIR"/lib/loop.sh
. "$SCRIPT_DIR"/lib/chroot.sh

### checks
check_root

### constants and variables
declare -r TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

declare -r WORK_DIR="/tmp/mkrootfs_$TIMESTAMP"
declare -r ROOTFS_DIR="$WORK_DIR/rootfs"
declare -r LOG_DIR="$WORK_DIR/log"

declare -r APT_CONFIG_DIR="$SCRIPT_DIR/config/apt"
declare -r PKGLIST_DIR="$SCRIPT_DIR/pkglist"

declare -r DEBIAN_MIRROR="http://deb.debian.org/debian"
declare -r UBUNTU_MIRROR="http://us.archive.ubuntu.com/ubuntu/"
# declare -r UBUNTU_MIRROR="https://mirror.arizona.edu/ubuntu/"
declare -r UBUNTU_PORT_MIRROR="http://ports.ubuntu.com/ubuntu-ports/"

# distro specific package lists
debian_included_deb_pkgs=(
    locales
    ca-certificates
)
debian_excluded_deb_pkgs=(
    ifupdown
)
ubuntu_included_deb_pkgs=()
ubuntu_excluded_deb_pkgs=(
    ubuntu-advantage-tools
    ubuntu-minimal
    ubuntu-pro-client
    ubuntu-pro-client-l10n
)
additional_deb_pkgs=(
    bash-completion
    zsh zsh-autosuggestions zsh-syntax-highlighting
    nano
    openssh-server
    curl wget git
    # screen tmux
)
kzl_pacman_pkgs=(
    base
    linux
)

distro=""
ubuntu_mirror=""
deb_mirror=""
deb_mirrors=()

included_deb_pkgs=()
excluded_deb_pkgs=()
pacman_pkgs=()

tarball_file=""

### options and arguments
arg_arch=""
arg_suite=""

### functions
cleanup() {
    set +e

    if [[ -d "$WORK_DIR" ]]; then
        info "Cleaning up..."
        chroot_teardown

        local _answer
        read -t 10 -p "Do you want to remove the working directory $WORK_DIR? (y/N) " _answer
        if [[ "$_answer" == "Y" || "$_answer" == "y" ]]; then
            info "Removing working directory: $WORK_DIR"
            rm -rf --one-file-system -- "$WORK_DIR"
            info "Done (Removed working directory)"
        fi
        info "Done (Cleaned up)"
    fi

    trap - EXIT SIGINT SIGTERM SIGKILL
}
trap cleanup EXIT SIGINT SIGTERM SIGKILL

make_work_dirs() {
    info "Making working directory: $WORK_DIR"
    if [[ -d "$WORK_DIR" ]]; then
        error "Working directory $WORK_DIR already exists" 1
    fi
    mkdir -p -- "$WORK_DIR"
    mkdir -p -- "$ROOTFS_DIR"
    mkdir -p -- "$LOG_DIR"
    if [[ ! -d "$PKGLIST_DIR" ]]; then
        mkdir -p -- "$PKGLIST_DIR"
        chown ${SUDO_UID:-0}:${SUDO_GID:-0} -- "$PKGLIST_DIR"
    fi
    info "Done (Made root filesystem directory)"
}

_debootstrap_rootfs() {
    local -r _deb_pkg_to_install="$PKGLIST_DIR/$arg_arch-$arg_suite-debootstrap-pkgs.txt"
    local -r _deb_pkgs_installed="$PKGLIST_DIR/$arg_arch-$arg_suite-rootfs-pkgs.txt"
    sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkg_to_install" "$_deb_pkgs_installed"

    local _include=""
    if (( ${#included_deb_pkgs[@]} > 0 )); then
        _include="--include=$(IFS=','; echo "${included_deb_pkgs[*]}")"
    fi

    local _exclude=""
    if (( ${#excluded_deb_pkgs[@]} > 0 )); then
        _exclude="--exclude=$(IFS=','; echo "${excluded_deb_pkgs[*]}")"
    fi

    info "Making the list of deb packages to be installed..."
    debootstrap \
        --print-debs \
        --arch="$arg_arch" \
        $_include \
        $_exclude \
        --merged-usr \
        "$arg_suite" \
        "$ROOTFS_DIR" \
        "$deb_mirror" \
        2> /dev/null | sed 's/ /\n/g' | LC_ALL=C sort -n  | sed '/^$/d' > "$_deb_pkg_to_install" || warn "Failed to creating the list of deb packages to be installed"
    info "Done (Made the list of installed deb packages)"

    info "Debootstrapping \"$ROOTFS_DIR/\"..."
    local _foreign=""
    if [[ "$arg_arch" != "$(dpkg --print-architecture)" ]]; then
        info "Using foreign architecture: $arg_arch"
        _foreign="--foreign"
    fi
    debootstrap \
        --arch="$arg_arch" \
        $_include \
        $_exclude \
        --merged-usr \
        $_foreign \
        "$arg_suite" \
        "$ROOTFS_DIR" \
        "$deb_mirror" \
        > "$LOG_DIR"/debootstrap.log 2>&1 || error "Failed to debootstrap rootfs" 2
    if [[ -n "$_foreign" ]]; then
        chroot "$ROOTFS_DIR" /debootstrap/debootstrap --second-stage >> "$LOG_DIR"/debootstrap.log 2>&1 || error "Failed to debootstrap (stage 2) rootfs" 3
    fi
    info "Done (Debootstrapped rootfs)"

    info "Setting up sources.list..."
    if [[ -f "$ROOTFS_DIR/etc/apt/sources.list" ]]; then
        mv -v -- "$ROOTFS_DIR/etc/apt/sources.list" "$ROOTFS_DIR/etc/apt/sources.list.bak"
    fi
    mkdir -vp -- "$ROOTFS_DIR/etc/apt/sources.list.d"
    if [[ "$arg_arch" != "amd64" && "$distro" == "ubuntu" ]]; then
        sed "s|@SUITE@|$arg_suite|g" "$APT_CONFIG_DIR/ubuntu-ports.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/ubuntu-ports.sources"
    else
        sed "s|@SUITE@|$arg_suite|g" "$APT_CONFIG_DIR/$distro.sources" > "$ROOTFS_DIR/etc/apt/sources.list.d/$distro.sources"
    fi
    info "Done (Set up sources.list)"

    info "Running chroot configuration..."
    chroot_setup "$ROOTFS_DIR" || error "Failed to setup chroot environment" 3
    # apt-get
    chroot_run "$ROOTFS_DIR" apt-get update || error "Failed to run apt-get update" 3
    chroot_run "$ROOTFS_DIR" apt-get upgrade -y || error "Failed to run apt-get upgrade" 3
    chroot_run "$ROOTFS_DIR" apt-get install --no-install-recommends -y "${additional_deb_pkgs[@]}" || error "Failed to run apt-get install" 3
    chroot_run "$ROOTFS_DIR" apt-get autoremove --purge -y || error "Failed to run apt-get autoremove" 3
    chroot_run "$ROOTFS_DIR" dpkg-reconfigure locales || warn "Failed to run dpkg-reconfigure locales"
    chroot_run "$ROOTFS_DIR" dpkg-reconfigure tzdata || warn "Failed to run dpkg-reconfigure tzdata"
    # get installed deb packages
    chroot_run "$ROOTFS_DIR" dpkg-query -W -f='${Package}\n' > "$_deb_pkgs_installed" || warn "Failed to get the list of installed deb packages"
    chroot_teardown
    info "Done (Chroot configuration)"

    info "Cleaning up rootfs..."
    clean_rootfs "$ROOTFS_DIR" > "$LOG_DIR/clean_rootfs.log"
    rm -vrf -- "$ROOTFS_DIR"/bin.usr-is-merged
    rm -vrf -- "$ROOTFS_DIR"/lib.usr-is-merged
    rm -vrf -- "$ROOTFS_DIR"/sbin.usr-is-merged
    info "Done (Cleaned up rootfs)"
}

_mmdebstrap_rootfs() {
    # local _deb_pkglist="${arg_suite}_deb_pkglist.txt"
    # sudo -u "${SUDO_USER:-root}" touch -- "$_deb_pkglist"

    # info "mmdebstrapping \"$ROOTFS_DIR/\": ${deb_pkgs[*]}"
    # mmdebstrap \
    #     --variant=- \
    #     --mode=root \
    #     --format=directory \
    #     --dpkgopt='path-exclude=/usr/share/doc/*' \
    #     --include="$(IFS=',' echo "${deb_pkgs[*]}")" \
    #     --architectures=arm64 \
    #     "$arg_suite" \
    #     "$ROOTFS_DIR" \
    #     "${deb_mirrors[@]}" \
    #     2>&1 | tee "$LOG_DIR/mmdebstrap.log" || error "Failed to mmdebstrap rootfs" 8
    # info "Done (mmdebstrapped rootfs)"
    error "Not implemented yet" 1
}

_pacstrap_rootfs() {
    # local -r _pkg_list="$PKGLIST_DIR/$arg_arch-pacstrap-pkgs.txt"
    # sudo -u "${SUDO_USER:-root}" touch -- "$_pkg_list"

    # mkdir -v -m 0755 -p "$ROOTFS_DIR"/var/{cache/pacman/pkg,lib/pacman,log} "$ROOTFS_DIR"/{dev,run,etc/pacman.d}
    # mkdir -v -m 1777 -p "$ROOTFS_DIR"/tmp
    # mkdir -v -m 0555 -p "$ROOTFS_DIR"/{sys,proc}
    error "Not implemented yet" 1
}

bootstrap_rootfs() {
    if [[ "$distro" == "debian" || "$distro" == "ubuntu" ]]; then
        _debootstrap_rootfs
        # _mmdebstrap_rootfs
    elif [[ "$distro" == "kzl-linux" ]]; then
        _pacstrap_rootfs
    else
        error "Unsupported distribution: $distro" 1
    fi
}

make_rootfs_tarball() {
    info "Making base rootfs tarball..."
    tar -v \
        --zstd \
        --xattrs --acls \
        --numeric-owner \
        --transform='s|^./||' \
        -cpf "$SCRIPT_DIR/$tarball_file" \
        -C "$ROOTFS_DIR" . \
        > "$LOG_DIR/tar.log" 2>&1 || error "Failed to make base rootfs tarball" 4
    chown ${SUDO_UID:-0}:${SUDO_GID:-0} "$SCRIPT_DIR/$tarball_file"
    info "Done (Made base rootfs tarball)"
}

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME  -a | --arch <architecture>  -s | --suite <suite>

    -h, --help                      print this help message and exit
    -a, --arch <architecture>       specify the platform
                                    supported platforms: amd64, arm64
    -s, --suite <suite>             specify the distribution suite
                                    supported suites: bookworm, trixie, jammy, noble, questing, kzl
EOF
}

################################################################################

while (( $# > 0 )); do
    case "$1" in
    -h | --help)
        usage
        exit 0
        ;;
    -a | --arch)
        shift
        arg_arch="$1"
        ;;
    -s | --suite)
        shift
        arg_suite="$1"
        ;;
    *)
        usage
        error "Unknown option: $1" 128
        ;;
    esac
    shift
done

case "$arg_arch" in
    amd64)
        ubuntu_mirror="$UBUNTU_MIRROR"
        ;;
    arm64)
        ubuntu_mirror="$UBUNTU_PORT_MIRROR"
        ;;
    *)
        usage
        error "Unsupported platform \"$arg_arch\"." 1
        ;;
esac

case "$arg_suite" in
    bookworm|trixie)
        distro="debian"
        deb_mirror="$DEBIAN_MIRROR"
        included_deb_pkgs=("${common_deb_pkgs[@]}" "${debian_included_deb_pkgs[@]}")
        excluded_deb_pkgs=("${debian_excluded_deb_pkgs[@]}")
        ;;
    jammy|noble|questing)
        distro="ubuntu"
        deb_mirror="$ubuntu_mirror"
        included_deb_pkgs=("${common_deb_pkgs[@]}" "${ubuntu_included_deb_pkgs[@]}")
        excluded_deb_pkgs=("${ubuntu_excluded_deb_pkgs[@]}")
        ;;
    kzl)
        distro="kzl-linux"
        pacman_pkgs=("${kzl_pacman_pkgs[@]}")
        ;;
    *)
        usage
        error "Unsupported distribution \"$arg_suite\"." 1
        ;;
esac

tarball_file="rootfs-$arg_arch-$distro-$arg_suite-$TIMESTAMP.tar.zst"

################################################################################

prologue

make_work_dirs
bootstrap_rootfs
make_rootfs_tarball

log_cyan "Successfully made rootfs tarball: $tarball_file"

cleanup

epilogue

### error codes
# 1: general error
# 2: debootstrap error
# 3: chroot error
# 4: tar error
# 128: unknown option
# 255: must be run as root
