post_install() {
  opt/TeXLive/bin/mktexlsr
  opt/TeXLive/bin/fmtutil-sys --all
  opt/TeXLive/bin/mtxrun --generate
}

post_upgrade() {
  post_install
}

# post_install() {
#   pkgver=$1
#   pkgver=${pkgver##*:}
#   pkgver=${pkgver%%-*}
#   bindir=opt/TeXLive/${pkgver:0:4}/bin/$(uname -m | sed -e 's/$/-linux/')
#   $bindir/mktexlsr
#   $bindir/fmtutil-sys --all
#   $bindir/mtxrun --generate
# }

# post_upgrade() {
#   post_install $1
# }
