#!/bin/bash
# 
# build_from_arch
#

VERSION=1.0
PKGDEST=~/makepkg/packages

# arguments

TARGET='x86_64'
STAGE='stage1'

# packages

stage1_pkgs=(
    linux-api-headers
    glibc
    binutils
    gcc
    libtool
)

stage2_pkgs=(
    binutils
    glibc
)

stage3_pkgs=(
    gcc
    libtool
    linux-api-headers
    glibc
    iana-etc
    tzdata
    zlib
    bzip2
    xz
    file
    readline
    m4
    ed
    bc
    binutils
    gmp
    mpfr
    mpc
    attr
    acl
    cracklib
    keyutils
    openssl
    libsasl
    openldap # libldap
    krb5
    libtirpc
    pam
    libcap-ng
    pcre
    swig
    audit
    shadow
    pkgconf
    ncurses
    libcap
    sed
    psmisc
    bison
    flex
    grep
    bash
    db
    gdbm
    expat
    perl
    diffutils
    autoconf
    automake
    kmod
    libunistring
    icu
    libxml2
    gettext
    elfutils
    gc
    libffi
    guile
    make
    libnsl
    mpdecimal
    tcl
    sqlite
    gdb
    valgrind
    python
    ninja
    meson
    coreutils
    gawk
    findutils
    less
    gzip
    zstd
    libmnl
    libnfnetlink
    libnetfilter_conntrack
    libnftnl
    libnl
    libusb
    libpcap
    iptables
    iproute2
    patch
    tar
    argon2
    libaio
    lapack
    cython
    python-numpy
    boost
    thin-provisioning-tools
    lvm2 #device-mapper
    json-c
    libgpg-error
    libgcrypt
    popt
    cryptsetup
    ca-certificates
    libidn2
    libnghttp2
    publicsuffix-list
    libpsl
    libssh2
    curl
    gnu-efi
    iptables
    check
    kbd
    libseccomp
    lz4
    libtasn1
    p11-kit
    pcre2
    libpng
    libpwquality
    qrencode
    gperf
    dbus
    systemd
    procps-ng
    util-linux
    e2fsprogs
    nettle
    gnutls
    libassuan
    libksba
    npth
    libusb-compat
    pcsclite
    gnupg
    swig
    gpgme
    libarchive
    pacman
    pacman-contrib
    git
    which
    sudo
    jsoncpp
    libuv
    rhash
    glib2
    itstool
    shared-mime-info
    cmake
    libedit
    libxslt
    iputils
    pciutils
    hidapi
    libcbor
    libfido2
    openssh
    rsync
    fakeroot
    arch-install-scripts
    dosfstools
    nano
    wpa_supplicant
    filesystem
    base
)

# functions

build() {
    local pkg
    pkg=$1

    cd "$scriptdir"/../core/$pkg

    local log
    log=$pkg.$STAGE.log
    if [[ -f $log ]]; then
        rm $log
    fi
    
    makepkg --config "$scriptdir"/../config/makepkg-$TARGET.conf -scCf --nocheck --noconfirm &>> $log

    case $pkg in
        openldap)
            sudo pacman -Udd --overwrite "*" $PKGDEST/libldap-[0-9]*.pkg.tar.zst --noconfirm
            ;;
        lvm2)
            sudo pacman -Udd --overwrite "*" $PKGDEST/device-mapper-[0-9]*.pkg.tar.zst --noconfirm
            ;;
        *)
            sudo pacman -Udd --overwrite "*" $PKGDEST/$pkg-[0-9]*.pkg.tar.zst --noconfirm
            ;;
    esac
}

usage() {
	printf "build_from_arch (kzl-linux) %s\n" "$VERSION"
	echo
	printf "build_from_arch will build from scratch.\n"
	echo
	printf "Usage: build_from_arch [options]\n"
	echo
	echo "    -h, --help        display this help message and exit"
	echo "    -v, --version     display version information and exit"
	echo "    -s, --stage       build stage (stage1, stage2, stage3)"
	echo "    -t, --target      target archtecture (x86_64, raspberrypi(armv7l))"
    echo
}

# program start

set -e -u -o pipefail
# set -x

# ensure we have a sane umask set
umask 0022

scriptdir=$(pwd)

while (( "$#" )); do
	case "$1" in
        -h|--help)      usage; exit 0 ;;
        -v|--version)   printf "$VERSION"; exit 0 ;;
        -s|--stage)     shift; STAGE="$1" ;;
        -t|--target)    shift; TARGET="$1" ;;
	esac
    shift
done

case $STAGE in
    stage1) pkgs=${stage1_pkgs[@]} ;;
    stage2) pkgs=${stage2_pkgs[@]} ;;
    stage3) pkgs=${stage3_pkgs[@]} ;;
    *)      printf "unknown stage \"$STAGE\""; exit 1 ;;
esac

for p in ${pkgs[@]}; do
    echo "building $p ..."
    build $p
done
