#!/bin/bash
# 
# update_checksum
#

set -e -u -o pipefail

scriptdir=$(pwd)

update() {
    local pkg
    pkg=$1

    cd "$pkg"

    updpkgsums
    gpg --recv-keys $(grep -E -o "[0-9A-F]{40}" PKGBUILD)
}

if [ $1 == linux ]; then
    update "$scriptdir"/../linux &
else
    for p in $(ls -d "$scriptdir"/../$1/*); do
        update $p &
    done
fi

wait
