#!/bin/bash
#
# build
#

set -e
set -o pipefail
# set -u
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

### libraries
. "$SCRIPT_DIR"/lib/log.sh
. "$SCRIPT_DIR"/lib/pacman.sh

### constants & variables
LOG_DIR="$HOME"/makepkg/log

### options and arguments
arg_repo=""
arg_single_package=""
declare -i opt_stage
declare -i opt_updatepkg=1
declare -i opt_updated_only=0
declare -i opt_install=0
declare -i opt_no_clean=0
declare -i opt_no_check=0

repo_pkgbuilds_dirs=()

### domain specific libraries
. "$SCRIPT_DIR"/pkglists.sh

### functions
prepare() {
    local _log="$LOG_DIR/prepare.log"

    sudo mkdir -vp /var/cache/makepkg/log
    sudo chown "${SUDO_UID}:${SUDO_GID}" -R /var/cache/makepkg
    ln -sf /var/cache/makepkg "$HOME/makepkg"

    info "Cleaning pacman cache and database..."
    sudo pacman -Scc --noconfirm
    info "Done (Cleaned pacman cache and database)"

    info "Updating repo..."
    updaterepo -r "$arg_repo" 2>&1 | tee -a "$_log"
    info "Done (Updated repo)"

    info "Synchronizing package databases..."
    sudo pacman -Syy --noconfirm
    info "Done (Synchronized package databases)"
}

_get_pkg_dir() {
    local _pkgbase="$1"
    local _pkgbuilds_dir
    readarray -t _pkgbuilds_dir < <(find "${repo_pkgbuilds_dirs[@]}" -mindepth 1 -maxdepth 1 -type d -name "$_pkgbase" -print)

    if (( ${#_pkgbuilds_dir[@]} != 1 )); then
        error "Failed to find package directory for \"$_pkgbase\"" 2
    fi

    info "Package directory: ${_pkgbuilds_dir[0]}"
    echo "${_pkgbuilds_dir[0]}"
}

build() {
    local _pkgname="$1"
    local _pkgbase=$(pacman_get_pkgbase "$_pkgname")
    local _log
    local -i _updated=0
    local _cleanbuild='-C'
    local _clean='--clean'
    local _no_check='--nocheck'

    if [[ -n "$opt_stage" ]]; then
        _log="$LOG_DIR/stage$opt_stage.$_pkgbase.log"
    else
        _log="$LOG_DIR/$_pkgbase.log"
    fi

    if [[ -f "$_log" ]]; then
        mv "$_log" "${_log/.log/.old.log}"
    fi

    cd $(_get_pkg_dir "$_pkgbase")

    # run install-dependencies.sh if exists
    if [[ -f "install-dependencies.sh" ]]; then
        info "Running install-dependencies.sh..."
        ./install-dependencies.sh >> "$_log" 2>&1
        info "Done (install-dependencies.sh)"
    fi

    # update pkgbuild
    if (( $opt_updatepkg > 0 )); then
        info "Updating PKGBUILD..."
        updatepkg --syncdeps >> "$_log" 2>&1 || _updated=$?
        _cleanbuild='-e'

        if (( $_updated == 255 )); then
            error "  Current version is newer" 3
        elif (( $_updated == 0 )); then
            info "  No update for PKGBUILD"
        elif (( $_updated == 1 )); then
            info "  Successfully updated package \"$_pkgbase\" to new version"
        elif (( $_updated == 2 )); then
            error "  PKGBUILD does not exist" 2
        elif (( $_updated == 3 )); then
            warn "  PKGUPDATE does not exist"
            _cleanbuild='-C'
        elif (( $_updated >= 4 )); then
            error "  Failed to update the PKGBUILD (error code: $_updated)" 3
        else
            error "  Unknown \`updatepkg\` result" 3
        fi

        if (( $opt_updated_only > 0 && $_updated == 0 )) && pacman -Q "$_pkgname" ;then
            # Package \"$_pkgbase\" is already the latest version, will not build (-u, --build-only-updated)
            info "Skip building"
            return
        fi
        if (( $_updated == 0 )); then
            updatepkg -I >> "$_log" 2>&1
        fi
        info "Done (PKGBUILD updated)"
    fi

    info "Building package..."
    if (( $opt_no_check == 0 )); then
        _no_check=''
    fi
    if (( $opt_no_clean > 0 )); then
        _clean=''
    fi

    makepkg -s -r "$_cleanbuild" -f "$_clean" "$_no_check" --noconfirm >> "$_log" 2>&1 || error "Failed to build package \"$_pkgbase\"" 1
    info "Done (Built package)"

    info "Getting package configuration log..."
        sed -n '/^  -> Configuring...$/,/^  -> Compiling...$/{/^  -> Configuring...$/b;/^  -> Compiling...$/b;p}' "$_log" > config.txt
        if [[ ! -s "config.txt" ]]; then
            rm config.txt
        fi
    info "Done (Got package configuration log)"

    info "Updating repo..."
    updaterepo -r "$arg_repo" >> "$_log" 2>&1
    sudo pacman -Sy 2>&1 | tee -a "$_log"
    info "Done (Updated repo)"

    if (( $opt_install > 0 )); then
        info "Installing package..."
        local -a _pkgnames=($(pacman_get_pkgnames "$_pkgname"))
        # sudo pacman -Sddy --noconfirm --overwrite "*" "${_pkgnames[@]}" --config $pacman_conf >> "$_log" 2>&1
        sudo pacman -S --noconfirm ${_pkgnames[@]} 2>&1 | tee -a "$_log"
        echo "Package Contents:" >> "$_log" 2>&1
        pacman -Ql "${_pkgnames[@]}" >> "$_log" 2>&1
        info "Done (Installed package)"
    fi
}

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME [ --no-updatepkg | --updated-only ] [ --no-check ] [ --no-clean ] -r <repo>  -s <stage> | -p <pkgname> [ --install ]
Usage: $SCRIPT_NAME [ -n | -u ] [ --no-check ] [ --no-clean ] -r <repo> -s <stage> | -p <pkgname> [ -i ]

    -h, --help                  display this help message and exit
    -r, --repo                  target repository (kzl, jammy, noble, ...)
    -s, --stage                 target stage (0, 1(default), 2, 3; some repo are not using this)
    -p, --package               build single package
    -n, --no-updatepkg          do not update the PKGBUILD before building
    -u, --updated-only          build the package only if the PKGBUILD is updated
    --no-clean                  skip cleaning up work files after build
    --no-check                  do not run the check() function in the PKGBUILD
    -i, --install               install the package after building

EOF
}

################################################################################

while (( $# > 0 )); do
    case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    -r|--repo)
        shift
        arg_repo="$1"
        ;;
    -s|--stage)
        shift
        opt_stage="$1"
        ;;
    -p|--package)
        shift
        arg_single_package="$1"
        ;;
    -n|--no-updatepkg)
        opt_updatepkg=0
        ;;
    -u|--updated-only)
        opt_updated_only=1
        ;;
    --no-clean)
        opt_no_clean=1
        ;;
    --no-check)
        opt_no_check=1
        ;;
    -i|--install)
        opt_install=1
        ;;
    *)
        usage
        error "Unknown option: \"$1\"" 128
        ;;
    esac
    shift
done

case "$arg_repo" in
    kzl)
        ;;
    jammy)
        ;;
    noble)
        ;;
    questing)
        ;;
    *)
        error "Unknown repo name \"$arg_repo\"" 128
        ;;
esac
repo_pkgbuilds_dirs+=("$LFS_PACMAN_ROOT_DIR/pkgbuilds/$arg_repo")

if (( $opt_updatepkg == 0 )) && (( $opt_updated_only == 1 )); then
    error "Cannot use --updated-only together with --no-updatepkg" 128
fi

if [[ -n "$arg_single_package" ]]; then
    if [[ -n "$opt_stage" ]]; then
        error "Cannot use -s | --stage together with -p | --package" 128
    fi
else
    stage=${stage:-1}
    case "$arg_repo" in
        kzl)
            case "$opt_stage" in
                0)
                    # updaterepo --clear -r "$arg_repo"
                    pkgs=("${kzl_stage0_pkgs[@]}")
                    ;;
                1)
                    pkgs=("${kzl_stage1_pkgs[@]}")
                    ;;
                2)
                    pkgs=("${kzl_stage2_pkgs[@]}")
                    ;;
                3)
                    pkgs=("${kzl_stage3_pkgs[@]}")
                    ;;
                *)
                    error "Unknown stage \"$opt_stage\"" 128
                    ;;
            esac
            ;;
        jammy|noble)
            case "$opt_stage" in
                0)
                    pkgs=("${ubuntu_stage0_pkgs[@]}")
                    ;;
                1)
                    pkgs=("${ubuntu_stage1_pkgs[@]}")
                    ;;
                2)
                    if (( opt_updated_only <= 0 )); then
                        warn "Better with --updated-only option"
                    fi
                    pkgs=("${ubuntu_stage2_pkgs[@]}")
                    ;;
                *)
                    error "Unknown stage \"$opt_stage\"" 128
                    ;;
            esac
            ;;
        questing)
            case "$opt_stage" in
                0)
                    pkgs=("${questing_stage0_pkgs[@]}")
                    ;;
                1)
                    pkgs=("${questing_stage1_pkgs[@]}")
                    ;;
                *)
                    error "Unknown stage \"$opt_stage\"" 128
                    ;;
            esac
            ;;
        *)
            error "Unknown repo name \"$arg_repo\" or the repo does not support stages" 128
            ;;
    esac
fi

################################################################################

prologue

prepare
if [[ -n "$arg_single_package" ]]; then
    # Build a single package
    log_magenta "Building $arg_single_package ($(date +%H:%M:%S))..."
    __pkg_start_time__=$(date +%s)
    build "$arg_single_package"
    __pkg_end_time__=$(date +%s)
    __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
    log_cyan "Finished $arg_single_package: $(date -d "@$__pkg_total_time__" +%H:%M:%S) ($(date +%H:%M:%S))"
else
    log_blue "Building stage $opt_stage ($(date +%H:%M:%S))..."
    for p in ${pkgs[@]}; do
        log_magenta "Building $p ($(date +%H:%M:%S))..."
        __pkg_start_time__=$(date +%s)
        build "$p"
        __pkg_end_time__=$(date +%s)
        __pkg_total_time__=$(($__pkg_end_time__ - $__pkg_start_time__))
        log_cyan "Finished $p: $(date -d "@$__pkg_total_time__" +%H:%M:%S) ($(date +%H:%M:%S))"
    done
fi

epilogue

### error codes
# 1: general error
# 2: package directory
# 3: updatepkg
# 128: unknown option or invalid argument
