#!/bin/bash
#
# chrootbuild.sh
#

set -e
set -o pipefail
set -u
# set -x

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$0"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

### libraries
. lib/log.sh
. lib/utils.sh
. lib/chroot.sh

### checks
check_root

### constants & variables
VERSION="1.0"

WORK_DIR="/tmp/chrootbuild"
ROOTFS_DIR="$WORK_DIR/rootfs"
CHROOT_HOME_DIR="home/kzl"
PACMAN_REPO_DIR="home/.repository/kzl"
PACMAN_REPO="$PACMAN_REPO_DIR/kzl.db"
WHEEL_DIR="$CHROOT_HOME_DIR/wheels"
PIP_CACHE_DIR="$WHEEL_DIR/.cache"
HOST_DIRS=(
    # host_dir:chroot_dir
    "$PACMAN_REPO_DIR:$PACMAN_REPO_DIR"
    "$CHROOT_HOME_DIR/LFS:$CHROOT_HOME_DIR/LFS"
    "$CHROOT_HOME_DIR/makepkg/sources:$CHROOT_HOME_DIR/makepkg/sources"
    "$CHROOT_HOME_DIR/chrootbuild/log:$CHROOT_HOME_DIR/makepkg/log"
    "$CHROOT_HOME_DIR/chrootbuild/archive:$CHROOT_HOME_DIR/makepkg/archive"
    "$CHROOT_HOME_DIR/chrootbuild/makepkglogs:$CHROOT_HOME_DIR/makepkg/makepkglogs"
    "$CHROOT_HOME_DIR/chrootbuild/wheels:$WHEEL_DIR"
    "$CHROOT_HOME_DIR/chrootbuild/wheels/.cache:$PIP_CACHE_DIR"
)
USERSPEC="kzl:kzl"

active_mounts=()
build_args=()

arg_rootfs_tarball=""
declare -i opt_backup=0
declare -i opt_clean=0
declare -i opt_from_rootfs_backups=0
declare -i opt_debug=0

### functions
backup() {
    info "Backing up rootfs..."
    if [[ -d "$ROOTFS_DIR" ]]; then
        tar --transform='s|^./||' --zstd -cpf chrootbuild_rootfs-$(date '+%Y%m%d_%H%M%S').tar.zst -C "$ROOTFS_DIR" .
        info "Done (Backing up rootfs)"
    else
        error "Rootfs directory ($ROOTFS_DIR) does not exist" 5
    fi
}

setup_rootfs() {
    local _rootfs_tarball="$1"
    local _from_rootfs_backups="$2"
    local _status_file="$WORK_DIR/${FUNCNAME[0]}"

    info "Setting up chroot environment..."

    if [[ ! -f "$_status_file" ]]; then
        if [[ -d "$ROOTFS_DIR" ]]; then
            error "Rootfs directory ($ROOTFS_DIR) exists but not set up, please delete first" 3
        fi

        if [[ ! -f "$_rootfs_tarball" ]]; then
            error "Please specify a rootfs tarball using \"-r <tarball>\"" 4
        fi
        info "Extracting rootfs tarball..."
        mkdir -p -- "$ROOTFS_DIR"
        tar -C "$ROOTFS_DIR" -xpf "$_rootfs_tarball"
        info "Done (Extracting rootfs tarball)"
    fi

    chroot_setup "$ROOTFS_DIR"

    info "Mounting LFS related directories..."
    for entry in "${HOST_DIRS[@]}"; do
        IFS=':' read -r src dest <<< "$entry"
        mkdir -p -- "/$src"
        mkdir -p -- "$ROOTFS_DIR/$dest"
        chroot_add_mount -v --bind "/$src" "$ROOTFS_DIR/$dest"
    done
    chown -R -- "$USERSPEC" "$ROOTFS_DIR/$CHROOT_HOME_DIR"
    info "Done (Mounting LFS related directories)"

    if (( $_from_rootfs_backups )); then
        info "Using rootfs opt_backups, skip configure the rootfs"
        touch "$_status_file"
    fi

    if [[ ! -f "$_status_file" ]]; then
        info "Configure chroot environment..."
        sed -i '/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^#//' "$ROOTFS_DIR"/etc/sudoers
        chroot_run "$ROOTFS_DIR" useradd -d "/$CHROOT_HOME_DIR" -G adm,wheel -U -s /bin/zsh kzl
        echo kzl:3450 | chroot_run "$ROOTFS_DIR" chpasswd
        chroot_run "$ROOTFS_DIR" su - kzl -c "cd LFS/kzl-linux/pacman && . ./setup.sh && updaterepo -r kzl"
        # chroot_run "$ROOTFS_DIR" pacman -Syu || :
        # chroot_run "$ROOTFS_DIR" pacman -Sy base-devel || :
        chroot_run "$ROOTFS_DIR" su - kzl -c "cd LFS/config && ./update-config.sh"
        chroot_run "$ROOTFS_DIR" su - kzl -c "python3 -m ensurepip"
        chroot_run "$ROOTFS_DIR" su - kzl -c "python3 -m pip wheel --wheel-dir /$WHEEL_DIR --cache-dir /$PIP_CACHE_DIR --no-binary :all: pip meson ninja"
        chroot_run "$ROOTFS_DIR" su - kzl -c "python3 -m pip install -U --no-index --find-links /$WHEEL_DIR --cache-dir /$PIP_CACHE_DIR pip meson ninja"
        info "Done (Configure chroot environment)"

        touch "$_status_file"
    fi

    info "Done (Setting up chroot environment)"
}

run_debug_shell() {
    chroot_run "$ROOTFS_DIR" /bin/zsh
}

run_build() {
    info "Running \`build\`..."
    chroot_run "$ROOTFS_DIR" su - kzl -c "source /$CHROOT_HOME_DIR/LFS/kzl-linux/pacman/setup.sh && build ${build_args[*]}"
    info "Done (Running \`build\`)"
}

unmount_all_bind_mounts() {
    while true; do
        local mountpoint
        readarray -t mountpoints < <(grep -F "$ROOTFS_DIR" /proc/mounts | awk '{print $2}' | LC_ALL=C sort -r)

        for mountpoint in "${mountpoints[@]}"; do
            umount -v -- "$mountpoint" || :
        done

        if (( ${#mountpoints[@]} == 0 )); then
            break
        fi

        error "Failed to unmount: \"${mountpoints[*]}\", try again"
        sleep 1
    done
}

remove_work_dir() {
    info "Removing working directory..."
    # must unmount all bind mounts before remove working directory, or bind mounts will be removed!!!
    unmount_all_bind_mounts
    rm -rf -- "$WORK_DIR"
    info "Done (Removing work directory)"
}

usage() {
    cat << EOF

Usage: $SCRIPT_NAME -h | --help
Usage: $SCRIPT_NAME -V | --version
Usage: $SCRIPT_NAME [ -r | --rootfs <tarball> ] [ -c | --clean ] [ -d | --debug ]
Usage: $SCRIPT_NAME [ -r | --rootfs <tarball> ] [ -c | --clean ] [ -b | --build <options passed to \`build\`> ]

General options:
    -h, --help                     show this help message and exit
    -V, --version                  show version and exit

Existing chrootbuild environment maintenance options:
    -c, --clean                     clean up work files and exit
    -B, --rootfs-backup             backup rootfs tarball

Chrootbuild environment setup options:
    -r, --rootfs <tarball>          rootfs tarball
    -e, --from-rootfs-backups       use rootfs backups, skip configure the rootfs

Chrootbuild environment debug options:
    -d, --debug                     enter debug shell

Chrootbuild options:
    -b, --build <options>           build options

EOF
}

clean() {
    info "Cleaning..."

    chroot_teardown
    unmount_all_bind_mounts

    info "Done (Cleaning)"

    trap - EXIT SIGINT SIGTERM SIGKILL
}
trap clean EXIT SIGINT SIGTERM SIGKILL

################################################################################

while (( $# > 0 )); do
    case "$1" in
    -r | --rootfs)
        shift
        arg_rootfs_tarball="${1:-}"
        ;;
    -B | --backup-rootfs)
        opt_backup=1
        ;;
    -e | --from-rootfs-backups)
        opt_from_rootfs_backups=1
        ;;
    -c | --clean)
        opt_clean=1
        ;;
    -d | --debug)
        opt_debug=1
        ;;
    -b | --build)
        shift
        build_args=("$@")
        break
        ;;
    -V | --version)
        echo "$version"
        exit
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    *)
        usage
        error "Unknown option: $1" 127
        ;;
    esac
    shift
done

if (( ${#build_args[@]} == 0 )); then
    build_args=('--help')
fi

################################################################################

prologue

if (( $opt_backup > 0 )); then
    backup
    epilogue
    exit
fi

if (( $opt_clean > 0 )); then
    remove_work_dir
    if [[ -z "$arg_rootfs_tarball" ]]; then
        epilogue
        exit
    fi
fi

setup_rootfs "$arg_rootfs_tarball" "$opt_from_rootfs_backups"
if (( $opt_debug > 0 )); then
    run_debug_shell
else
    run_build
fi
clean

epilogue

### error codes
# 1: must be run as root
# 2: failed to unmount
# 3: working directory already exists
# 4: rootfs tarball not specified
# 5: failed to opt_backup rootfs
