#!/bin/bash
#
# updpkgsums
#
# https://gitlab.archlinux.org/pacman/pacman-contrib/-/raw/master/src/updpkgsums.sh.in
#

set -e
# set -u
set -o pipefail
# set -x

umask 0022

SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

################################################################################

### libraries
. "$SCRIPT_DIR"/lib/log.sh

### constants & variables
PKGBUILDDIR="$(pwd)"
PKGBUILD_FILE="PKGBUILD"
NEW_PKGBUILD_FILE="PKGBUILD.updpkgsums"

### functions
usage() {
    cat << EOF

Update checksums of a PKGBUILD file

Usage: $SCRIPT_NAME
EOF
}

################################################################################

if [[ ! -f "$PKGBUILD_FILE" ]]; then
   error "PKGBUILD does not exist" 2
fi

if [[ -f "/usr/share/makepkg/util/schema.sh" ]]; then
    . /usr/share/makepkg/util/schema.sh
elif [[ -f "/opt/share/makepkg/util/schema.sh" ]]; then
    . /opt/share/makepkg/util/schema.sh
else
    error '<libmakepkgdir>/util/schema.sh not found' 3
fi

info "Getting known hash algorithms..."
sumtypes=$(IFS='|'; echo "${known_hash_algos[*]}")
info "Done (Got known hash algorithms)"

info "Running \`makepkg -g\`..."
newsums=$(makepkg -g)
if (( $? )); then
    error "\`makepkg -g\` failed" 4
fi
info "Done (Ran \`makepkg -g\`)"

if [[ -z $newsums ]]; then
    error "No sources to update checksums" 5
fi

awk -v sumtypes="$sumtypes" -v newsums="$newsums" '
    $0 ~ "^[[:blank:]]*(" sumtypes ")sums(_[^=]+)?\\+?=",
	$0 ~ "^[^)]*\\)[[:blank:]]*(#.*)?$" {
        if (!w) {
            print newsums
            w++
        }
        next
    }

    1
    END { if (!w) print newsums }
' "$PKGBUILD_FILE" > "$NEW_PKGBUILD_FILE" || error 'Failed to write new PKGBUILD' 6
trap 'rm -rf "$NEW_PKGBUILD_FILE"' EXIT

if ! cat -- "$NEW_PKGBUILD_FILE" > "$PKGBUILD_FILE"; then
    error "Failed to update $PKGBUILD_FILE" 6
fi

### error codes
# 1: general error
# 2: PKGBUILD does not exist
# 3: schema.sh NOT found
# 4: `makepkg -g` error
# 5: no sources to update checksums
# 6: failed to update PKGBUILD
